# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: de

pipeline:
  - name: SpacyNLP
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    retrieval_intent: faq
    epochs: 100
  - name: ResponseSelector
    retrieval_intent: chitchat
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.8
    ambiguity_threshold: 0.1
  - name: fallback.SingleTokenFallbackClassifier
    threshold: 0.95
    intent_name: single_word
    maximum_num_tokens: 1

policies:
  - name: MemoizationPolicy
    max_history: 2
  - name: TEDPolicy
    max_history: 2
    epochs: 100
  - name: RulePolicy
